version: "3.8"
services:
  mongodb:
    container_name: mongodb4.4
    hostname: ${MONGO_HOSTNAME}
    image: mongo:4.4.0
    volumes:
      - ./data/db:/data/db
      - ./scripts/mongoinit:/docker-entrypoint-initdb.d:ro
    ports:
      - 35000:27017
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    healthcheck:
      test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo -u $${MONGO_INITDB_ROOT_USERNAME} -p $${MONGO_INITDB_ROOT_PASSWORD} --quiet) -eq 1
      interval: 10s
      start_period: 30s
    command: mongod --replSet ${MONGO_REPLICA_SET_NAME}

  redis:
    image: redis:6-alpine
    hostname: ${REDIS_HOSTNAME}
    volumes:
      - ./data/redis:/data
    entrypoint: redis-server --appendonly yes
    restart: always
    ports:
      - 6400:6379

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:${REDIS_HOSTNAME}:6379
    ports:
      - "6500:8081"